// Generated by Framer (9805f18)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "31hijo"}], description: siteMetadata(params, activeLocale).description, elements: {}, framerSearch: {index: false}, robots: "noindex", serializationId: "framer-KLYNe", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=1200"}
}

export const metadataVersion = 1