// Generated by Framer (9805f18)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "kzcyy"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-ddtVa", title: siteMetadata(params, activeLocale).title || "Portfolio", viewport: "width=1200"}
}

export const metadataVersion = 1