// Generated by Framer (3ef9ea7)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "72rtr7", mediaQuery: "(min-width: 1200px)"}, {hash: "hl6v98", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "6tact1", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {azBSYe1me: "card-1", c3aE0ZsIp: "card-2", DKGpjrEX3: "card-3", UFe2ohR9B: "cards", vKmi2iN4S: "about"}, robots: "max-image-preview:large", serializationId: "framer-vK1eJ", socialImage: "https://framerusercontent.com/assets/Rf8zWc2T6zVsrABCdIoWtdai428.png", title: siteMetadata(params, activeLocale).title || "Home", viewport: "width=device-width"}
}

export const metadataVersion = 1