// Generated by Framer (b47b624)

import { getWhereExpressionFromPathVariables, QueryEngine } from "framer";
import Work from "../collection/Nn7b1zcLz";
import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
	return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const gnzp2TOto = params?.["gnzp2TOto"]
return {breakpoints: [{hash: "ln80fh", mediaQuery: "(min-width: 1200px)"}, {hash: "1ncz3rh", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "dzgpqk", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {GSzb9oIcR: "overlap"}, robots: "max-image-preview:large", serializationId: "framer-FF40V", socialImage: "https://framerusercontent.com/assets/Rf8zWc2T6zVsrABCdIoWtdai428.png", title: `${gnzp2TOto !== undefined ? toString(gnzp2TOto) : "{{gnzp2TOto}}"} - Fuel - Premium Agency & Portfolio`, viewport: "width=device-width"}
}

export async function fetchMetadata(pathVariables, activeLocale) {
  const queryEngine = new QueryEngine();

  const query = {from: {alias: "UANVURkgl", data: Work, type: "Collection"}, select: [{collection: "UANVURkgl", name: "gnzp2TOto", type: "Identifier"}], where: getWhereExpressionFromPathVariables(pathVariables, "UANVURkgl")};

  const result = await queryEngine.query(query, activeLocale);
  if (result.length === 0) {
    throw new Error("No data matches pathVariables");
  }

  const params = result[0];
  return metadata(params, activeLocale);
}

export async function fetchAllMetadata(pathVariableKeys, activeLocale) {
  const queryEngine = new QueryEngine();

  const query = {from: {alias: "UANVURkgl", data: Work, type: "Collection"}, select: [{collection: "UANVURkgl", name: "gnzp2TOto", type: "Identifier"}]};

  for (const pathVariableKey of pathVariableKeys) {
    query.select.push({
      collection: "UANVURkgl",
      name: pathVariableKey,
      type: "Identifier",
    });
  }

  const results = await queryEngine.query(query, activeLocale);

  return results.map(result => ({
    metadata: metadata(result, activeLocale),
    pathVariables: Object.fromEntries(
      pathVariableKeys.map(pathVariableKey => [pathVariableKey, result[pathVariableKey]])
    )
  }));
}

export const metadataVersion = 1