// Generated by Framer (77d7dc9)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1xejt8c", mediaQuery: "(min-width: 1200px)"}, {hash: "u13ke3", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1400n70", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {mlhrtsMAM: "about"}, robots: "max-image-preview:large", serializationId: "framer-RIlXY", socialImage: "https://framerusercontent.com/assets/Rf8zWc2T6zVsrABCdIoWtdai428.png", title: siteMetadata(params, activeLocale).title || "About", viewport: "width=device-width"}
}

export const metadataVersion = 1