// Generated by Framer (aabb2d2)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1mm62il", mediaQuery: "(min-width: 1200px)"}, {hash: "1frjr6x", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1i07uwr", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {pElGoNUJu: "work", ZmQXYm2iM: "card-1"}, robots: "max-image-preview:large", serializationId: "framer-N8FT9", socialImage: "https://framerusercontent.com/assets/Rf8zWc2T6zVsrABCdIoWtdai428.png", title: siteMetadata(params, activeLocale).title || "Work / Portfolio", viewport: "width=device-width"}
}

export const metadataVersion = 1