// Generated by Framer (dc4b6d1)

import { getWhereExpressionFromPathVariables, QueryEngine } from "framer";
import Blog from "../collection/n6kHvb78k";
import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const nMuFmvxK0 = params?.["nMuFmvxK0"]
return {breakpoints: [{hash: "tjjh3m", mediaQuery: "(min-width: 1200px)"}, {hash: "xjx3jj", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1qalz1i", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {mTMTq_iQH: "detail"}, robots: "max-image-preview:large", serializationId: "framer-2QQch", socialImage: "https://framerusercontent.com/assets/Rf8zWc2T6zVsrABCdIoWtdai428.png", title: `${nMuFmvxK0 !== undefined ? toString(nMuFmvxK0) : "{{nMuFmvxK0}}"} - Fuel - Premium Agency & Portfolio`, viewport: "width=device-width"}
}

export async function fetchMetadata(pathVariables, activeLocale) {
  const queryEngine = new QueryEngine();

  const query = {from: {alias: "xFr4pT0XQ", data: Blog, type: "Collection"}, select: [{collection: "xFr4pT0XQ", name: "nMuFmvxK0", type: "Identifier"}], where: getWhereExpressionFromPathVariables(pathVariables, "xFr4pT0XQ")};

  const result = await queryEngine.query(query, activeLocale);
  if (result.length === 0) {
    throw new Error("No data matches pathVariables");
  }

  const params = result[0];
  return metadata(params, activeLocale);
}

export async function fetchAllMetadata(pathVariableKeys, activeLocale) {
  const queryEngine = new QueryEngine();

  const query = {from: {alias: "xFr4pT0XQ", data: Blog, type: "Collection"}, select: [{collection: "xFr4pT0XQ", name: "nMuFmvxK0", type: "Identifier"}]};

  for (const pathVariableKey of pathVariableKeys) {
    query.select.push({
      collection: "xFr4pT0XQ",
      name: pathVariableKey,
      type: "Identifier",
    });
  }

  const results = await queryEngine.query(query, activeLocale);

  return results.map(result => ({
    metadata: metadata(result, activeLocale),
    pathVariables: Object.fromEntries(
      pathVariableKeys.map(pathVariableKey => [pathVariableKey, result[pathVariableKey]])
    )
  }));
}

export const metadataVersion = 1