// Generated by Framer (9805f18)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "nmj56o"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-I9kVb", title: siteMetadata(params, activeLocale).title || "Page", viewport: "width=1200"}
}

export const metadataVersion = 1