// Generated by Framer (9805f18)

import { addFonts, addPropertyControls, ControlType, cx, getLoadingLazyAtYPosition, Image, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";

const serializationHash = "framer-Ab1Db"

const variantClassNames = {yeupk3YAN: "framer-v-1i14bq4"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {bounce: 0.2, delay: 0, duration: 0.4, type: "spring"}

const toResponsiveImage = (value) => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value
    }
    return typeof value === "string" ? {src: value} : undefined;
};


const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const getProps = ({height, id, image, width, ...props}) => { return {...props, tmIAlb2UT: image ?? props.tmIAlb2UT ?? {alt: "", pixelHeight: 64, pixelWidth: 302, src: "https://framerusercontent.com/images/4Zx7DVBTo5PGL5e1p7CD0XPVHqU.png?width=302&height=64"}} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;image?: {src: string; srcSet?: string; alt?: string}; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const { style, className, layoutId, variant, tmIAlb2UT, ...restProps } = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({defaultVariant: "yeupk3YAN", ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const sharedStyleClassNames = []

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(scopingClassNames, "framer-1i14bq4", className, classNames)} data-framer-name={"Primary"} layoutDependency={layoutDependency} layoutId={"yeupk3YAN"} ref={refBinding} style={{backgroundColor: "var(--token-66c37500-d629-41e0-8a75-d54a632a5687, rgb(247, 247, 247))", borderBottomLeftRadius: 5, borderBottomRightRadius: 5, borderTopLeftRadius: 5, borderTopRightRadius: 5, ...style}}><Image background={{alt: "", fit: "fit", loading: getLoadingLazyAtYPosition(((componentViewport?.y || 0) + 0 + (((((componentViewport?.height || 168) - 0) - 16) / 2) + 0 + 0))), pixelHeight: 64, pixelWidth: 302, sizes: "104px", ...toResponsiveImage(tmIAlb2UT), ...{ positionX: "center", positionY: "center" }}} className={"framer-1atv9y3"} layoutDependency={layoutDependency} layoutId={"ZtBEBl6Qu"}/></motion.div></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Ab1Db.framer-1jpvigz, .framer-Ab1Db .framer-1jpvigz { display: block; }", ".framer-Ab1Db.framer-1i14bq4 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 168px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 224px; will-change: var(--framer-will-change-override, transform); }", ".framer-Ab1Db .framer-1atv9y3 { flex: none; height: 16px; overflow: visible; position: relative; width: 104px; }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 168
 * @framerIntrinsicWidth 224
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"tmIAlb2UT":"image"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerFz10EBZk9: React.ComponentType<Props> = withCSS(Component, css, "framer-Ab1Db") as typeof Component;
export default FramerFz10EBZk9;

FramerFz10EBZk9.displayName = "Client Card";

FramerFz10EBZk9.defaultProps = {height: 168, width: 224};

addPropertyControls(FramerFz10EBZk9, {tmIAlb2UT: {__defaultAssetReference: "data:framer/asset-reference,4Zx7DVBTo5PGL5e1p7CD0XPVHqU.png?originalFilename=111.png&width=302&height=64", __vekterDefault: {alt: "", assetReference: "data:framer/asset-reference,4Zx7DVBTo5PGL5e1p7CD0XPVHqU.png?originalFilename=111.png&width=302&height=64"}, title: "Image", type: ControlType.ResponsiveImage}} as any)

addFonts(FramerFz10EBZk9, [{explicitInter: true, fonts: []}], {supportsExplicitInterCodegen: true})