// Generated by Framer (569b461)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "17e0s8x"}], description: siteMetadata(params, activeLocale).description, elements: {jfGRqdJqs: "about"}, robots: "max-image-preview:large", serializationId: "framer-BABj2", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=1440"}
}

export const metadataVersion = 1