// Generated by Framer (dc4b6d1)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "17u14kv", mediaQuery: "(min-width: 1200px)"}, {hash: "1ir815i", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1l5htqn", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-XA72c", socialImage: "https://framerusercontent.com/assets/Rf8zWc2T6zVsrABCdIoWtdai428.png", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=device-width"}
}

export const metadataVersion = 1