// Generated by Framer (9805f18)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1igqclb"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-amQ26", title: siteMetadata(params, activeLocale).title || "Contact", viewport: "width=1200"}
}

export const metadataVersion = 1