// Generated by Framer (c9d77eb)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "bceerf", mediaQuery: "(min-width: 1200px)"}, {hash: "8nj3ah", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1csimh7", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-5TQfM", socialImage: "https://framerusercontent.com/assets/Rf8zWc2T6zVsrABCdIoWtdai428.png", title: siteMetadata(params, activeLocale).title || "Contact", viewport: "width=device-width"}
}

export const metadataVersion = 1